/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.102
 * Generated at: 2025-04-15 12:36:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.liferay.layout.content.page.editor.web.internal.constants.ContentPageEditorWebKeys;
import com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext;
import com.liferay.layout.content.page.editor.web.internal.display.context.EditCollectionConfigurationDisplayContext;
import com.liferay.petra.string.StringPool;
import com.liferay.portal.kernel.feature.flag.FeatureFlagManagerUtil;
import com.liferay.portal.kernel.language.LanguageUtil;
import com.liferay.portal.kernel.util.ParamUtil;
import com.liferay.portal.kernel.util.PortalUtil;

public final class view_005ftoolbar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/init.jsp", Long.valueOf(1743464318000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(11);
    _jspx_imports_classes.add("com.liferay.portal.kernel.feature.flag.FeatureFlagManagerUtil");
    _jspx_imports_classes.add("com.liferay.petra.string.StringPool");
    _jspx_imports_classes.add("com.liferay.layout.content.page.editor.web.internal.constants.ContentPageEditorWebKeys");
    _jspx_imports_classes.add("com.liferay.portal.kernel.language.LanguageUtil");
    _jspx_imports_classes.add("com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContext");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.PortalUtil");
    _jspx_imports_classes.add("com.liferay.portal.kernel.util.ParamUtil");
    _jspx_imports_classes.add("com.liferay.layout.content.page.editor.web.internal.display.context.EditCollectionConfigurationDisplayContext");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      //  liferay-frontend:defineObjects
      com.liferay.frontend.taglib.servlet.taglib.DefineObjectsTag _jspx_th_liferay_002dfrontend_005fdefineObjects_005f0 = new com.liferay.frontend.taglib.servlet.taglib.DefineObjectsTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dfrontend_005fdefineObjects_005f0);
      _jspx_th_liferay_002dfrontend_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
      _jspx_th_liferay_002dfrontend_005fdefineObjects_005f0.setParent(null);
      int _jspx_eval_liferay_002dfrontend_005fdefineObjects_005f0 = _jspx_th_liferay_002dfrontend_005fdefineObjects_005f0.doStartTag();
      if (_jspx_th_liferay_002dfrontend_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dfrontend_005fdefineObjects_005f0, _jsp_getInstanceManager());
      java.lang.String currentURL = null;
      javax.portlet.PortletURL currentURLObj = null;
      java.lang.String npmResolvedPackageName = null;
      java.util.ResourceBundle resourceBundle = null;
      javax.portlet.WindowState windowState = null;
      currentURL = (java.lang.String) _jspx_page_context.findAttribute("currentURL");
      currentURLObj = (javax.portlet.PortletURL) _jspx_page_context.findAttribute("currentURLObj");
      npmResolvedPackageName = (java.lang.String) _jspx_page_context.findAttribute("npmResolvedPackageName");
      resourceBundle = (java.util.ResourceBundle) _jspx_page_context.findAttribute("resourceBundle");
      windowState = (javax.portlet.WindowState) _jspx_page_context.findAttribute("windowState");
      out.write('\n');
      out.write('\n');
      //  liferay-theme:defineObjects
      com.liferay.taglib.theme.DefineObjectsTag _jspx_th_liferay_002dtheme_005fdefineObjects_005f0 = new com.liferay.taglib.theme.DefineObjectsTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0);
      _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
      _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.setParent(null);
      int _jspx_eval_liferay_002dtheme_005fdefineObjects_005f0 = _jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doStartTag();
      if (_jspx_th_liferay_002dtheme_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dtheme_005fdefineObjects_005f0, _jsp_getInstanceManager());
      com.liferay.portal.kernel.theme.ThemeDisplay themeDisplay = null;
      com.liferay.portal.kernel.model.Company company = null;
      com.liferay.portal.kernel.model.User user = null;
      com.liferay.portal.kernel.model.User realUser = null;
      com.liferay.portal.kernel.model.Contact contact = null;
      com.liferay.portal.kernel.model.Layout layout = null;
      java.util.List layouts = null;
      java.lang.Long plid = null;
      com.liferay.portal.kernel.model.LayoutTypePortlet layoutTypePortlet = null;
      java.lang.Long scopeGroupId = null;
      com.liferay.portal.kernel.security.permission.PermissionChecker permissionChecker = null;
      java.util.Locale locale = null;
      java.util.TimeZone timeZone = null;
      com.liferay.portal.kernel.model.Theme theme = null;
      com.liferay.portal.kernel.model.ColorScheme colorScheme = null;
      com.liferay.portal.kernel.theme.PortletDisplay portletDisplay = null;
      java.lang.Long portletGroupId = null;
      themeDisplay = (com.liferay.portal.kernel.theme.ThemeDisplay) _jspx_page_context.findAttribute("themeDisplay");
      company = (com.liferay.portal.kernel.model.Company) _jspx_page_context.findAttribute("company");
      user = (com.liferay.portal.kernel.model.User) _jspx_page_context.findAttribute("user");
      realUser = (com.liferay.portal.kernel.model.User) _jspx_page_context.findAttribute("realUser");
      contact = (com.liferay.portal.kernel.model.Contact) _jspx_page_context.findAttribute("contact");
      layout = (com.liferay.portal.kernel.model.Layout) _jspx_page_context.findAttribute("layout");
      layouts = (java.util.List) _jspx_page_context.findAttribute("layouts");
      plid = (java.lang.Long) _jspx_page_context.findAttribute("plid");
      layoutTypePortlet = (com.liferay.portal.kernel.model.LayoutTypePortlet) _jspx_page_context.findAttribute("layoutTypePortlet");
      scopeGroupId = (java.lang.Long) _jspx_page_context.findAttribute("scopeGroupId");
      permissionChecker = (com.liferay.portal.kernel.security.permission.PermissionChecker) _jspx_page_context.findAttribute("permissionChecker");
      locale = (java.util.Locale) _jspx_page_context.findAttribute("locale");
      timeZone = (java.util.TimeZone) _jspx_page_context.findAttribute("timeZone");
      theme = (com.liferay.portal.kernel.model.Theme) _jspx_page_context.findAttribute("theme");
      colorScheme = (com.liferay.portal.kernel.model.ColorScheme) _jspx_page_context.findAttribute("colorScheme");
      portletDisplay = (com.liferay.portal.kernel.theme.PortletDisplay) _jspx_page_context.findAttribute("portletDisplay");
      portletGroupId = (java.lang.Long) _jspx_page_context.findAttribute("portletGroupId");
      out.write('\n');
      out.write('\n');
      //  portlet:defineObjects
      com.liferay.taglib.portlet.DefineObjectsTag _jspx_th_portlet_005fdefineObjects_005f0 = new com.liferay.taglib.portlet.DefineObjectsTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_portlet_005fdefineObjects_005f0);
      _jspx_th_portlet_005fdefineObjects_005f0.setPageContext(_jspx_page_context);
      _jspx_th_portlet_005fdefineObjects_005f0.setParent(null);
      int _jspx_eval_portlet_005fdefineObjects_005f0 = _jspx_th_portlet_005fdefineObjects_005f0.doStartTag();
      if (_jspx_th_portlet_005fdefineObjects_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_portlet_005fdefineObjects_005f0, _jsp_getInstanceManager());
      javax.portlet.ActionRequest actionRequest = null;
      javax.portlet.ActionResponse actionResponse = null;
      javax.portlet.EventRequest eventRequest = null;
      javax.portlet.EventResponse eventResponse = null;
      com.liferay.portal.kernel.portlet.LiferayPortletRequest liferayPortletRequest = null;
      com.liferay.portal.kernel.portlet.LiferayPortletResponse liferayPortletResponse = null;
      javax.portlet.PortletConfig portletConfig = null;
      java.lang.String portletName = null;
      javax.portlet.PortletPreferences portletPreferences = null;
      java.util.Map portletPreferencesValues = null;
      javax.portlet.PortletSession portletSession = null;
      java.util.Map portletSessionScope = null;
      javax.portlet.RenderRequest renderRequest = null;
      javax.portlet.RenderResponse renderResponse = null;
      javax.portlet.ResourceRequest resourceRequest = null;
      javax.portlet.ResourceResponse resourceResponse = null;
      actionRequest = (javax.portlet.ActionRequest) _jspx_page_context.findAttribute("actionRequest");
      actionResponse = (javax.portlet.ActionResponse) _jspx_page_context.findAttribute("actionResponse");
      eventRequest = (javax.portlet.EventRequest) _jspx_page_context.findAttribute("eventRequest");
      eventResponse = (javax.portlet.EventResponse) _jspx_page_context.findAttribute("eventResponse");
      liferayPortletRequest = (com.liferay.portal.kernel.portlet.LiferayPortletRequest) _jspx_page_context.findAttribute("liferayPortletRequest");
      liferayPortletResponse = (com.liferay.portal.kernel.portlet.LiferayPortletResponse) _jspx_page_context.findAttribute("liferayPortletResponse");
      portletConfig = (javax.portlet.PortletConfig) _jspx_page_context.findAttribute("portletConfig");
      portletName = (java.lang.String) _jspx_page_context.findAttribute("portletName");
      portletPreferences = (javax.portlet.PortletPreferences) _jspx_page_context.findAttribute("portletPreferences");
      portletPreferencesValues = (java.util.Map) _jspx_page_context.findAttribute("portletPreferencesValues");
      portletSession = (javax.portlet.PortletSession) _jspx_page_context.findAttribute("portletSession");
      portletSessionScope = (java.util.Map) _jspx_page_context.findAttribute("portletSessionScope");
      renderRequest = (javax.portlet.RenderRequest) _jspx_page_context.findAttribute("renderRequest");
      renderResponse = (javax.portlet.RenderResponse) _jspx_page_context.findAttribute("renderResponse");
      resourceRequest = (javax.portlet.ResourceRequest) _jspx_page_context.findAttribute("resourceRequest");
      resourceResponse = (javax.portlet.ResourceResponse) _jspx_page_context.findAttribute("resourceResponse");
      out.write('\n');
      out.write('\n');

ContentPageEditorDisplayContext contentPageEditorDisplayContext = (ContentPageEditorDisplayContext)request.getAttribute(ContentPageEditorWebKeys.LIFERAY_SHARED_CONTENT_PAGE_EDITOR_DISPLAY_CONTEXT);

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"management-bar navbar navbar-expand-md page-editor__toolbar ");
      out.print( contentPageEditorDisplayContext.isMasterLayout() ? "page-editor__toolbar--master-layout" : StringPool.BLANK );
      out.write("\" id=\"");
      out.print( contentPageEditorDisplayContext.getPortletNamespace() );
      out.write("pageEditorToolbar\">\n");
      out.write("	");
      //  clay:container-fluid
      com.liferay.frontend.taglib.clay.servlet.taglib.ContainerFluidTag _jspx_th_clay_005fcontainer_002dfluid_005f0 = new com.liferay.frontend.taglib.clay.servlet.taglib.ContainerFluidTag();
      _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fcontainer_002dfluid_005f0);
      _jspx_th_clay_005fcontainer_002dfluid_005f0.setPageContext(_jspx_page_context);
      _jspx_th_clay_005fcontainer_002dfluid_005f0.setParent(null);
      // /view_toolbar.jsp(15,1) name = fullWidth type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_clay_005fcontainer_002dfluid_005f0.setFullWidth( FeatureFlagManagerUtil.isEnabled("LPS-184404") );
      int _jspx_eval_clay_005fcontainer_002dfluid_005f0 = _jspx_th_clay_005fcontainer_002dfluid_005f0.doStartTag();
      if (_jspx_eval_clay_005fcontainer_002dfluid_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\n");
        out.write("		<ul class=\"navbar-nav start\">\n");
        out.write("			<li class=\"nav-item\">\n");
        out.write("				<div class=\"dropdown\">\n");
        out.write("					");
        //  clay:button
        com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f0 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f0);
        _jspx_th_clay_005fbutton_005f0.setPageContext(_jspx_page_context);
        _jspx_th_clay_005fbutton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(21,5) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f0.setCssClass("dropdown-toggle");
        // /view_toolbar.jsp(21,5) null
        _jspx_th_clay_005fbutton_005f0.setDynamicAttribute(null, "disabled",  true );
        // /view_toolbar.jsp(21,5) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f0.setDisplayType("secondary");
        // /view_toolbar.jsp(21,5) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f0.setIcon("en-us");
        // /view_toolbar.jsp(21,5) name = monospaced type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f0.setMonospaced( true );
        // /view_toolbar.jsp(21,5) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f0.setSmall( true );
        int _jspx_eval_clay_005fbutton_005f0 = _jspx_th_clay_005fbutton_005f0.doStartTag();
        if (_jspx_th_clay_005fbutton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f0, _jsp_getInstanceManager());
        out.write("\n");
        out.write("				</div>\n");
        out.write("			</li>\n");
        out.write("		</ul>\n");
        out.write("\n");
        out.write("		<ul class=\"middle navbar-nav\">\n");
        out.write("			<li class=\"nav-item\"></li>\n");
        out.write("		</ul>\n");
        out.write("\n");
        out.write("		<ul class=\"end navbar-nav\">\n");
        out.write("			<li class=\"nav-item\"></li>\n");
        out.write("\n");
        out.write("			<li class=\"d-lg-flex d-none nav-item\">\n");
        out.write("				<div class=\"btn-group flex-nowrap\" role=\"group\">\n");
        out.write("					");
        //  clay:button
        com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f1 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f1);
        _jspx_th_clay_005fbutton_005f1.setPageContext(_jspx_page_context);
        _jspx_th_clay_005fbutton_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(42,5) null
        _jspx_th_clay_005fbutton_005f1.setDynamicAttribute(null, "disabled",  true );
        // /view_toolbar.jsp(42,5) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f1.setDisplayType("secondary");
        // /view_toolbar.jsp(42,5) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f1.setIcon("undo");
        // /view_toolbar.jsp(42,5) name = monospaced type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f1.setMonospaced( true );
        // /view_toolbar.jsp(42,5) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f1.setSmall( true );
        // /view_toolbar.jsp(42,5) null
        _jspx_th_clay_005fbutton_005f1.setDynamicAttribute(null, "title", "undo");
        int _jspx_eval_clay_005fbutton_005f1 = _jspx_th_clay_005fbutton_005f1.doStartTag();
        if (_jspx_th_clay_005fbutton_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f1, _jsp_getInstanceManager());
        out.write("\n");
        out.write("\n");
        out.write("					");
        //  clay:button
        com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f2 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f2);
        _jspx_th_clay_005fbutton_005f2.setPageContext(_jspx_page_context);
        _jspx_th_clay_005fbutton_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(51,5) null
        _jspx_th_clay_005fbutton_005f2.setDynamicAttribute(null, "disabled",  true );
        // /view_toolbar.jsp(51,5) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f2.setDisplayType("secondary");
        // /view_toolbar.jsp(51,5) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f2.setIcon("redo");
        // /view_toolbar.jsp(51,5) name = monospaced type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f2.setMonospaced( true );
        // /view_toolbar.jsp(51,5) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f2.setSmall( true );
        // /view_toolbar.jsp(51,5) null
        _jspx_th_clay_005fbutton_005f2.setDynamicAttribute(null, "title", "redo");
        int _jspx_eval_clay_005fbutton_005f2 = _jspx_th_clay_005fbutton_005f2.doStartTag();
        if (_jspx_th_clay_005fbutton_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f2, _jsp_getInstanceManager());
        out.write("\n");
        out.write("				</div>\n");
        out.write("\n");
        out.write("				<span class=\"d-none d-sm-block ml-2\">\n");
        out.write("					");
        //  clay:button
        com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f3 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f3);
        _jspx_th_clay_005fbutton_005f3.setPageContext(_jspx_page_context);
        _jspx_th_clay_005fbutton_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(62,5) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f3.setCssClass("dropdown-toggle");
        // /view_toolbar.jsp(62,5) null
        _jspx_th_clay_005fbutton_005f3.setDynamicAttribute(null, "disabled",  true );
        // /view_toolbar.jsp(62,5) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f3.setDisplayType("secondary");
        // /view_toolbar.jsp(62,5) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f3.setIcon("time");
        // /view_toolbar.jsp(62,5) name = monospaced type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f3.setMonospaced( true );
        // /view_toolbar.jsp(62,5) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f3.setSmall( true );
        // /view_toolbar.jsp(62,5) null
        _jspx_th_clay_005fbutton_005f3.setDynamicAttribute(null, "title", "history");
        int _jspx_eval_clay_005fbutton_005f3 = _jspx_th_clay_005fbutton_005f3.doStartTag();
        if (_jspx_th_clay_005fbutton_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f3, _jsp_getInstanceManager());
        out.write("\n");
        out.write("				</span>\n");
        out.write("			</li>\n");
        out.write("			<li class=\"d-lg-flex d-none nav-item\">\n");
        out.write("				<div class=\"dropdown\">\n");
        out.write("					");
        //  clay:button
        com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f4 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f4);
        _jspx_th_clay_005fbutton_005f4.setPageContext(_jspx_page_context);
        _jspx_th_clay_005fbutton_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(75,5) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f4.setCssClass("form-control-select");
        // /view_toolbar.jsp(75,5) null
        _jspx_th_clay_005fbutton_005f4.setDynamicAttribute(null, "disabled",  true );
        // /view_toolbar.jsp(75,5) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f4.setDisplayType("secondary");
        // /view_toolbar.jsp(75,5) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f4.setSmall( true );
        int _jspx_eval_clay_005fbutton_005f4 = _jspx_th_clay_005fbutton_005f4.doStartTag();
        if (_jspx_eval_clay_005fbutton_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write("\n");
          out.write("						");
          if (_jspx_meth_liferay_002dui_005fmessage_005f0(_jspx_th_clay_005fbutton_005f4, _jspx_page_context))
            return;
          out.write("\n");
          out.write("					");
        }
        if (_jspx_th_clay_005fbutton_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f4, _jsp_getInstanceManager());
        out.write("\n");
        out.write("				</div>\n");
        out.write("			</li>\n");
        out.write("			<li class=\"d-lg-none nav-item\">\n");
        out.write("				");
        //  clay:button
        com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f5 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f5);
        _jspx_th_clay_005fbutton_005f5.setPageContext(_jspx_page_context);
        _jspx_th_clay_005fbutton_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(86,4) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f5.setCssClass("form-control-select");
        // /view_toolbar.jsp(86,4) null
        _jspx_th_clay_005fbutton_005f5.setDynamicAttribute(null, "disabled",  true );
        // /view_toolbar.jsp(86,4) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f5.setDisplayType("secondary");
        // /view_toolbar.jsp(86,4) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f5.setIcon("format");
        // /view_toolbar.jsp(86,4) name = monospaced type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f5.setMonospaced( false );
        // /view_toolbar.jsp(86,4) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f5.setSmall( true );
        int _jspx_eval_clay_005fbutton_005f5 = _jspx_th_clay_005fbutton_005f5.doStartTag();
        if (_jspx_th_clay_005fbutton_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f5, _jsp_getInstanceManager());
        out.write("\n");
        out.write("			</li>\n");
        out.write("			<li class=\"d-lg-flex d-none nav-item\">\n");
        out.write("				");
        //  clay:button
        com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f6 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f6);
        _jspx_th_clay_005fbutton_005f6.setPageContext(_jspx_page_context);
        _jspx_th_clay_005fbutton_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(96,4) null
        _jspx_th_clay_005fbutton_005f6.setDynamicAttribute(null, "disabled",  true );
        // /view_toolbar.jsp(96,4) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f6.setDisplayType("secondary");
        // /view_toolbar.jsp(96,4) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f6.setIcon("view");
        // /view_toolbar.jsp(96,4) name = monospaced type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f6.setMonospaced( true );
        // /view_toolbar.jsp(96,4) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f6.setSmall( true );
        // /view_toolbar.jsp(96,4) null
        _jspx_th_clay_005fbutton_005f6.setDynamicAttribute(null, "title", "view");
        int _jspx_eval_clay_005fbutton_005f6 = _jspx_th_clay_005fbutton_005f6.doStartTag();
        if (_jspx_th_clay_005fbutton_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f6, _jsp_getInstanceManager());
        out.write("\n");
        out.write("			</li>\n");
        out.write("			<li class=\"d-lg-flex d-none nav-item\">\n");
        out.write("				");
        //  clay:button
        com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f7 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f7);
        _jspx_th_clay_005fbutton_005f7.setPageContext(_jspx_page_context);
        _jspx_th_clay_005fbutton_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(106,4) null
        _jspx_th_clay_005fbutton_005f7.setDynamicAttribute(null, "disabled",  true );
        // /view_toolbar.jsp(106,4) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f7.setDisplayType("secondary");
        // /view_toolbar.jsp(106,4) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f7.setSmall( true );
        int _jspx_eval_clay_005fbutton_005f7 = _jspx_th_clay_005fbutton_005f7.doStartTag();
        if (_jspx_eval_clay_005fbutton_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write("\n");
          out.write("					");
          if (_jspx_meth_liferay_002dui_005fmessage_005f1(_jspx_th_clay_005fbutton_005f7, _jspx_page_context))
            return;
          out.write("\n");
          out.write("				");
        }
        if (_jspx_th_clay_005fbutton_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f7, _jsp_getInstanceManager());
        out.write("\n");
        out.write("			</li>\n");
        out.write("			<li class=\"d-lg-none nav-item\">\n");
        out.write("				");
        //  clay:button
        com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f8 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f8);
        _jspx_th_clay_005fbutton_005f8.setPageContext(_jspx_page_context);
        _jspx_th_clay_005fbutton_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(115,4) null
        _jspx_th_clay_005fbutton_005f8.setDynamicAttribute(null, "disabled",  true );
        // /view_toolbar.jsp(115,4) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f8.setDisplayType("secondary");
        // /view_toolbar.jsp(115,4) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f8.setIcon("ellipsis-v");
        // /view_toolbar.jsp(115,4) name = monospaced type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f8.setMonospaced( true );
        // /view_toolbar.jsp(115,4) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f8.setSmall( true );
        int _jspx_eval_clay_005fbutton_005f8 = _jspx_th_clay_005fbutton_005f8.doStartTag();
        if (_jspx_th_clay_005fbutton_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f8, _jsp_getInstanceManager());
        out.write("\n");
        out.write("			</li>\n");
        out.write("\n");
        out.write("			");
        //  c:if
        org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = new org.apache.taglibs.standard.tag.rt.core.IfTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(124,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest( contentPageEditorDisplayContext.isSingleSegmentsExperienceMode() );
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("				<li class=\"nav-item\">\n");
            out.write("					");
            //  clay:button
            com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f9 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
            _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f9);
            _jspx_th_clay_005fbutton_005f9.setPageContext(_jspx_page_context);
            _jspx_th_clay_005fbutton_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
            // /view_toolbar.jsp(126,5) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_clay_005fbutton_005f9.setCssClass("mr-3");
            // /view_toolbar.jsp(126,5) null
            _jspx_th_clay_005fbutton_005f9.setDynamicAttribute(null, "disabled",  true );
            // /view_toolbar.jsp(126,5) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_clay_005fbutton_005f9.setDisplayType("secondary");
            // /view_toolbar.jsp(126,5) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
            _jspx_th_clay_005fbutton_005f9.setSmall( true );
            int _jspx_eval_clay_005fbutton_005f9 = _jspx_th_clay_005fbutton_005f9.doStartTag();
            if (_jspx_eval_clay_005fbutton_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
              out.write("\n");
              out.write("						");
              if (_jspx_meth_liferay_002dui_005fmessage_005f2(_jspx_th_clay_005fbutton_005f9, _jspx_page_context))
                return;
              out.write("\n");
              out.write("					");
            }
            if (_jspx_th_clay_005fbutton_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
              return;
            }
            org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f9, _jsp_getInstanceManager());
            out.write("\n");
            out.write("				</li>\n");
            out.write("			");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager());
        out.write("\n");
        out.write("\n");
        out.write("			<li class=\"nav-item\">\n");
        out.write("				");
        //  clay:button
        com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f10 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f10);
        _jspx_th_clay_005fbutton_005f10.setPageContext(_jspx_page_context);
        _jspx_th_clay_005fbutton_005f10.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(138,4) null
        _jspx_th_clay_005fbutton_005f10.setDynamicAttribute(null, "disabled",  true );
        // /view_toolbar.jsp(138,4) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f10.setDisplayType("primary");
        // /view_toolbar.jsp(138,4) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f10.setSmall( true );
        int _jspx_eval_clay_005fbutton_005f10 = _jspx_th_clay_005fbutton_005f10.doStartTag();
        if (_jspx_eval_clay_005fbutton_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write("\n");
          out.write("					");
          //  c:choose
          org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = new org.apache.taglibs.standard.tag.common.core.ChooseTag();
          _jsp_getInstanceManager().newInstance(_jspx_th_c_005fchoose_005f0);
          _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fchoose_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fbutton_005f10);
          int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
          if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\n");
              out.write("						");
              //  c:when
              org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = new org.apache.taglibs.standard.tag.rt.core.WhenTag();
              _jsp_getInstanceManager().newInstance(_jspx_th_c_005fwhen_005f0);
              _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /view_toolbar.jsp(144,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f0.setTest( contentPageEditorDisplayContext.isMasterLayout() );
              int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
              if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("							");
                  if (_jspx_meth_liferay_002dui_005fmessage_005f3(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("						");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager());
              out.write("\n");
              out.write("						");
              //  c:when
              org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = new org.apache.taglibs.standard.tag.rt.core.WhenTag();
              _jsp_getInstanceManager().newInstance(_jspx_th_c_005fwhen_005f1);
              _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /view_toolbar.jsp(147,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f1.setTest( contentPageEditorDisplayContext.isSingleSegmentsExperienceMode() );
              int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
              if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("							");
                  if (_jspx_meth_liferay_002dui_005fmessage_005f4(_jspx_th_c_005fwhen_005f1, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("						");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager());
              out.write("\n");
              out.write("						");
              //  c:when
              org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f2 = new org.apache.taglibs.standard.tag.rt.core.WhenTag();
              _jsp_getInstanceManager().newInstance(_jspx_th_c_005fwhen_005f2);
              _jspx_th_c_005fwhen_005f2.setPageContext(_jspx_page_context);
              _jspx_th_c_005fwhen_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
              // /view_toolbar.jsp(150,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
              _jspx_th_c_005fwhen_005f2.setTest( contentPageEditorDisplayContext.isWorkflowEnabled() );
              int _jspx_eval_c_005fwhen_005f2 = _jspx_th_c_005fwhen_005f2.doStartTag();
              if (_jspx_eval_c_005fwhen_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
                do {
                  out.write("\n");
                  out.write("							");
                  if (_jspx_meth_liferay_002dui_005fmessage_005f5(_jspx_th_c_005fwhen_005f2, _jspx_page_context))
                    return;
                  out.write("\n");
                  out.write("						");
                  int evalDoAfterBody = _jspx_th_c_005fwhen_005f2.doAfterBody();
                  if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                    break;
                } while (true);
              }
              if (_jspx_th_c_005fwhen_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
                return;
              }
              org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f2, _jsp_getInstanceManager());
              out.write("\n");
              out.write("						");
              if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
                return;
              out.write("\n");
              out.write("					");
              int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
          org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager());
          out.write("\n");
          out.write("				");
        }
        if (_jspx_th_clay_005fbutton_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f10, _jsp_getInstanceManager());
        out.write("\n");
        out.write("			</li>\n");
        out.write("			<li class=\"d-md-none nav-item\">\n");
        out.write("				");
        //  clay:button
        com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag _jspx_th_clay_005fbutton_005f11 = new com.liferay.frontend.taglib.clay.servlet.taglib.ButtonTag();
        _jsp_getInstanceManager().newInstance(_jspx_th_clay_005fbutton_005f11);
        _jspx_th_clay_005fbutton_005f11.setPageContext(_jspx_page_context);
        _jspx_th_clay_005fbutton_005f11.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fcontainer_002dfluid_005f0);
        // /view_toolbar.jsp(160,4) name = cssClass type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f11.setCssClass("text-secondary");
        // /view_toolbar.jsp(160,4) null
        _jspx_th_clay_005fbutton_005f11.setDynamicAttribute(null, "disabled",  true );
        // /view_toolbar.jsp(160,4) name = displayType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f11.setDisplayType("unstyled");
        // /view_toolbar.jsp(160,4) name = icon type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f11.setIcon("cog");
        // /view_toolbar.jsp(160,4) name = monospaced type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f11.setMonospaced( true );
        // /view_toolbar.jsp(160,4) name = small type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_clay_005fbutton_005f11.setSmall( true );
        int _jspx_eval_clay_005fbutton_005f11 = _jspx_th_clay_005fbutton_005f11.doStartTag();
        if (_jspx_th_clay_005fbutton_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fbutton_005f11, _jsp_getInstanceManager());
        out.write("\n");
        out.write("			</li>\n");
        out.write("		</ul>\n");
        out.write("	");
      }
      if (_jspx_th_clay_005fcontainer_002dfluid_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return;
      }
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_clay_005fcontainer_002dfluid_005f0, _jsp_getInstanceManager());
      out.write("\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_liferay_002dui_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_clay_005fbutton_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  liferay-ui:message
    com.liferay.taglib.ui.MessageTag _jspx_th_liferay_002dui_005fmessage_005f0 = new com.liferay.taglib.ui.MessageTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dui_005fmessage_005f0);
    _jspx_th_liferay_002dui_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_liferay_002dui_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fbutton_005f4);
    // /view_toolbar.jsp(81,6) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_liferay_002dui_005fmessage_005f0.setKey("page-design");
    int _jspx_eval_liferay_002dui_005fmessage_005f0 = _jspx_th_liferay_002dui_005fmessage_005f0.doStartTag();
    if (_jspx_th_liferay_002dui_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dui_005fmessage_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_liferay_002dui_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_clay_005fbutton_005f7, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  liferay-ui:message
    com.liferay.taglib.ui.MessageTag _jspx_th_liferay_002dui_005fmessage_005f1 = new com.liferay.taglib.ui.MessageTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dui_005fmessage_005f1);
    _jspx_th_liferay_002dui_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_liferay_002dui_005fmessage_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fbutton_005f7);
    // /view_toolbar.jsp(111,5) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_liferay_002dui_005fmessage_005f1.setKey("discard-draft");
    int _jspx_eval_liferay_002dui_005fmessage_005f1 = _jspx_th_liferay_002dui_005fmessage_005f1.doStartTag();
    if (_jspx_th_liferay_002dui_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dui_005fmessage_005f1, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_liferay_002dui_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_clay_005fbutton_005f9, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  liferay-ui:message
    com.liferay.taglib.ui.MessageTag _jspx_th_liferay_002dui_005fmessage_005f2 = new com.liferay.taglib.ui.MessageTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dui_005fmessage_005f2);
    _jspx_th_liferay_002dui_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_liferay_002dui_005fmessage_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_clay_005fbutton_005f9);
    // /view_toolbar.jsp(132,6) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_liferay_002dui_005fmessage_005f2.setKey("discard-variant");
    int _jspx_eval_liferay_002dui_005fmessage_005f2 = _jspx_th_liferay_002dui_005fmessage_005f2.doStartTag();
    if (_jspx_th_liferay_002dui_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dui_005fmessage_005f2, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_liferay_002dui_005fmessage_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  liferay-ui:message
    com.liferay.taglib.ui.MessageTag _jspx_th_liferay_002dui_005fmessage_005f3 = new com.liferay.taglib.ui.MessageTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dui_005fmessage_005f3);
    _jspx_th_liferay_002dui_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_liferay_002dui_005fmessage_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
    // /view_toolbar.jsp(145,7) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_liferay_002dui_005fmessage_005f3.setKey("publish-master");
    int _jspx_eval_liferay_002dui_005fmessage_005f3 = _jspx_th_liferay_002dui_005fmessage_005f3.doStartTag();
    if (_jspx_th_liferay_002dui_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dui_005fmessage_005f3, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_liferay_002dui_005fmessage_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  liferay-ui:message
    com.liferay.taglib.ui.MessageTag _jspx_th_liferay_002dui_005fmessage_005f4 = new com.liferay.taglib.ui.MessageTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dui_005fmessage_005f4);
    _jspx_th_liferay_002dui_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_liferay_002dui_005fmessage_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
    // /view_toolbar.jsp(148,7) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_liferay_002dui_005fmessage_005f4.setKey("save-variant");
    int _jspx_eval_liferay_002dui_005fmessage_005f4 = _jspx_th_liferay_002dui_005fmessage_005f4.doStartTag();
    if (_jspx_th_liferay_002dui_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dui_005fmessage_005f4, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_liferay_002dui_005fmessage_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  liferay-ui:message
    com.liferay.taglib.ui.MessageTag _jspx_th_liferay_002dui_005fmessage_005f5 = new com.liferay.taglib.ui.MessageTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dui_005fmessage_005f5);
    _jspx_th_liferay_002dui_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_liferay_002dui_005fmessage_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f2);
    // /view_toolbar.jsp(151,7) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_liferay_002dui_005fmessage_005f5.setKey("submit-for-workflow");
    int _jspx_eval_liferay_002dui_005fmessage_005f5 = _jspx_th_liferay_002dui_005fmessage_005f5.doStartTag();
    if (_jspx_th_liferay_002dui_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dui_005fmessage_005f5, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = new org.apache.taglibs.standard.tag.common.core.OtherwiseTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_c_005fotherwise_005f0);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("							");
        if (_jspx_meth_liferay_002dui_005fmessage_005f6(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
          return true;
        out.write("\n");
        out.write("						");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_liferay_002dui_005fmessage_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  liferay-ui:message
    com.liferay.taglib.ui.MessageTag _jspx_th_liferay_002dui_005fmessage_005f6 = new com.liferay.taglib.ui.MessageTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_liferay_002dui_005fmessage_005f6);
    _jspx_th_liferay_002dui_005fmessage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_liferay_002dui_005fmessage_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
    // /view_toolbar.jsp(154,7) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_liferay_002dui_005fmessage_005f6.setKey("publish");
    int _jspx_eval_liferay_002dui_005fmessage_005f6 = _jspx_th_liferay_002dui_005fmessage_005f6.doStartTag();
    if (_jspx_th_liferay_002dui_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_liferay_002dui_005fmessage_005f6, _jsp_getInstanceManager());
    return false;
  }
}
